### 회원 가입

POST http://localhost:10362/api/users
Accept: application/json
Content-Type: application/json

{
  "name": "이성계",
  "password": "123",
  "email": "qwer12@naver.com",
  "phoneNumber": "010-1111-2222",
  "birthDate": "1996-06-24",
  "address": "지호로 39번길"
}

### 로그인
POST http://localhost:10362/api/users/login
Content-Type: application/json

{
  "email": "qwer12345@naver.com",
  "password": "123"
}

### 유저 찾기
GET http://localhost:10362/api/users/me
X-User-Id: 2

### 유저 삭제
DELETE http://localhost:10362/api/users/me
X-User-Id: 1


### 주소 추가
POST http://localhost:10362/api/address
Content-Type: application/json
X-User-Id: 1

{
  "nickName": "내집",
  "streetAddress": "일산"
}

### 주소 조회
GET http://localhost:10362/api/address
X-User-Id: 1

### 주소 삭제
DELETE http://localhost:10362/api/address/2
X-User-Id: 1

### 이번달 생일인 유저들 조회
GET http://localhost:10362/api/users/birth



