server:
  port: 10362
spring:
  application:
    name: account-api
  data:
    redis:
      database: 315
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      timeout: 2000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # ?? ??? ?? ???

management:
  endpoint:
    web:
      exposure:
        include: health, info

token:
  secret: 12345678910111213141516171819202122