server:
  port: 10362
spring:
  application:
    name: account-api
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/be10-team4?useSSL=false&serverTimezone=UTC
    username: project_be10_team4
    password: uEUklnkbk*7*_O4H
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true